// Type declarations for coverage.json — auto-generated by jest --json --outputFile=coverage.json.
// The file is gitignored so we need this declaration for CI type-checking.

interface CoverageAssertionResult {
  ancestorTitles: string[]
  fullName: string
  status: 'passed' | 'failed' | 'pending' | 'todo'
  title: string
  duration: number | null
  failureMessages: string[]
  location: unknown | null
  meta: Record<string, unknown>
}

interface CoverageTestResult {
  assertionResults: CoverageAssertionResult[]
  endTime: number
  message: string
  name: string
  startTime: number
  status: 'passed' | 'failed'
  summary: string
}

declare const coverageData: {
  numFailedTestSuites: number
  numFailedTests: number
  numPassedTestSuites: number
  numPassedTests: number
  numPendingTestSuites: number
  numPendingTests: number
  numRuntimeErrorTestSuites: number
  numTodoTests: number
  numTotalTestSuites: number
  numTotalTests: number
  openHandles: unknown[]
  snapshot: Record<string, unknown>
  startTime: number
  success: boolean
  testResults: CoverageTestResult[]
  wasInterrupted: boolean
}

export default coverageData
