// Stub for coverage.json — auto-generated by jest --json --outputFile=coverage.json.
// Gitignored at build time, so all tests resolve to this stub via jest moduleNameMapper.
interface CoverageAssertionResult {
  ancestorTitles: string[]
  fullName: string
  status: 'passed' | 'failed' | 'pending' | 'todo'
  title: string
  duration: number | null
  failureMessages: string[]
  location: unknown | null
  meta: Record<string, unknown>
}

interface CoverageTestResult {
  assertionResults: CoverageAssertionResult[]
  endTime: number
  message: string
  name: string
  startTime: number
  status: 'passed' | 'failed'
  summary: string
}

const coverageData: {
  numFailedTestSuites: number
  numFailedTests: number
  numPassedTestSuites: number
  numPassedTests: number
  numPendingTestSuites: number
  numPendingTests: number
  numRuntimeErrorTestSuites: number
  numTodoTests: number
  numTotalTestSuites: number
  numTotalTests: number
  openHandles: unknown[]
  snapshot: Record<string, unknown>
  startTime: number
  success: boolean
  testResults: CoverageTestResult[]
  wasInterrupted: boolean
} = {
  numFailedTestSuites: 0,
  numFailedTests: 0,
  numPassedTestSuites: 0,
  numPassedTests: 0,
  numPendingTestSuites: 0,
  numPendingTests: 0,
  numRuntimeErrorTestSuites: 0,
  numTodoTests: 0,
  numTotalTestSuites: 0,
  numTotalTests: 0,
  openHandles: [],
  snapshot: {},
  startTime: 0,
  success: true,
  testResults: [],
  wasInterrupted: false,
}

export default coverageData
