import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const DOCS_DIR = path.join(__dirname, '../docs')
const OUTPUT_FILE = path.join(__dirname, '../src/lib/services/vfsData.ts')

function buildVfsNode(dirPath, name = '/') {
  const stats = fs.statSync(dirPath)
  const node = {
    name,
    type: stats.isDirectory() ? 'dir' : 'file',
    permissions: stats.isDirectory() ? 'drwxr-xr-x' : '-rw-r--r--',
  }

  if (stats.isDirectory()) {
    node.children = {}
    const items = fs.readdirSync(dirPath)
    for (const item of items) {
      if (item.startsWith('.') || item === 'api' || item === 'content-audit.md') continue
      const fullPath = path.join(dirPath, item)
      node.children[item] = buildVfsNode(fullPath, item)
    }
  } else {
    // Only include content for markdown files, and limit size
    if (name.endsWith('.md')) {
      const content = fs.readFileSync(dirPath, 'utf8')
      node.content =
        content.length > 5000 ? content.slice(0, 5000) + '\n\n[Content truncated...]' : content
    }
  }

  return node
}

try {
  const docsNode = buildVfsNode(DOCS_DIR, 'docs')

  const vfsData = {
    name: '/',
    type: 'dir',
    permissions: 'drwxr-xr-x',
    children: {
      docs: docsNode,
      projects: {
        name: 'projects',
        type: 'dir',
        children: {},
        permissions: 'drwxr-xr-x',
      },
      'README.md': {
        name: 'README.md',
        type: 'file',
        content:
          '# Jonathan Verdun Portfolio\nQA Automation Engineer & Bioinformatics Researcher.\n\nType "ls projects" to see work history, or "cd docs" to read audits.',
        permissions: '-rw-r--r--',
      },
    },
  }

  const content = `/**
 * @file vfsData.ts
 * Autogenerated Virtual File System data from the docs directory.
 * Generated on: ${new Date().toISOString()}
 */

import { VFSNode } from './VirtualFileSystem'

export const VFS_DATA: VFSNode = ${JSON.stringify(vfsData, null, 2)}
`

  fs.writeFileSync(OUTPUT_FILE, content)
  console.log('Successfully generated VFS data at src/lib/services/vfsData.ts')
} catch (err) {
  console.error('Failed to generate VFS data:', err)
  process.exit(1)
}
